### ISSUE TITLE
Doesn't work with Xcode Version 6.2 (6C131e)

### ISSUE THREAD

**Issue by cbscd** [questbeat/Lin#42]

**Comment by questbeat** [comment]
It worked on my Xcode (6.2, 6C131e).
Are you using the latest release?

**Comment by cbscd** [comment]
Hi,  
Yes it is the latest release. 


Xcode 6.2
Updated: Mar 09, 2015
Build: 6C131e
SDK: iOS 8.2, OS X v10.10

**Comment by questbeat** [comment]
Sorry for my lack of explanation.
Are you also using the latest **Lin**?
Latest commit added the UUID of Xcode 6.2.

**Comment by cbscd** [comment]
Oh, I see what you meant. 
I guess I am.  I'm using Alcatraz to install it.

**Comment by questbeat** [comment]
OK, I found a solution.
Alcatraz uses cached data, so the old version is used even if you reinstall the plug-in.
Please follow the steps below to fix the problem.

1. Remove all cached data of Alcatraz: `rm -rf ~/Library/Application\ Support/Alcatraz`
2. Reinstall Lin and restart your Xcode.

**Comment by questbeat** [comment]
@cbscd Was this confirmed?
I wrote about this in the [README](https://github.com/questbeat/Lin/blob/master/README.md), and I'd like to close this issue.

**Comment by cbscd** [comment]
Hi,

Sorry for the late response.

Yes, this is confirmed to work!

I appreciate your help!

Daniel

**Comment by questbeat** [comment]
:smiley:
