### ISSUE TITLE
How to custom auto complete key word ?

### ISSUE THREAD

**Issue by com314159** [questbeat/Lin#44]
say I have define my own macro called "KSLocalizedString"

this plug not worked for this.  

One solution is to add key bind to auto complete,
The other is to define my own key word. 

can you tell me how to do it ? 

thank you

**Comment by com314159** [comment]
In completion.plist, I found it

**Comment by questbeat** [comment]
OK, solved?
I think [this](https://github.com/questbeat/Lin/issues/41) might be helpful.

**Comment by com314159** [comment]
solved, thank you
