### ISSUE TITLE
Doesn't work with Xcode Version 6.4 (6E35b)

### ISSUE THREAD

**Issue by scmstom** [questbeat/Lin#50]

**Comment by jasper2007111** [comment]
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`


work for me

**Comment by questbeat** [comment]
Released [3.1.4](https://github.com/questbeat/Lin/releases/tag/3.1.4).

**Comment by scmstom** [comment]
It's working now.
Thanks.
