### ISSUE TITLE
Not working for Xcode 7.2 (7C68)

### ISSUE THREAD

**Issue by yiboyu** [questbeat/Lin#59]
@antonjn Any fixes? =)

**Comment by raheelahmad786** [comment]
Same here just downloaded and build it, not showing in toolbar xCode editor section.

**Comment by questbeat** [comment]
It works on my Xcode 7.2 (7C68) so I need more information.

e.g.
- Do you use Alcatraz or not
- Swift or Obj-C
- How many `strings` files are contained in your project
- Which function do you use to localize string

**Comment by raheelahmad786** [comment]
Hi,

1. Do you use Alcatraz or not
No i am not using it. Using the manual process.
2. Swift or Obj-C
Objective-C
3. How many strings files are contained in your project
300+
4. Which function do you use to localize string
NSLocalizedString

**Comment by questbeat** [comment]
@raheelahmad786

Thanks.

> Same here just downloaded and build it, not showing in toolbar xCode editor section.

Does this mean that the auto-completion popup is not shown?
Or the popup is shown but there are no correct items?

**Comment by yiboyu** [comment]
@questbeat If I may speak for him, the auto-completion popup is not showing at all.

**Comment by yiboyu** [comment]
Just upgraded to Xcode 7.2.1(7C1002) and it seems to be working again =)

Closing this issue.
